[package]
name = "iced_baseview"
version = "0.0.3"
authors = [
  "Billy Messenger <BillyDM@protonmail.com>",
  "Robbert van der Helm <mail@robbertvanderhelm.nl>",
  "Joakim Frostegård <joakim.frostegard@gmail.com>",
]
edition = "2021"
description = "A baseview runtime for Iced (WIP)"
license = "MIT"
repository = "https://github.com/BillyDM/iced_baseview"
documentation = "https://docs.rs/iced_baseview"
keywords = ["gui", "ui", "graphics", "interface", "widgets"]
categories = ["gui"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["wgpu"]

# Enables the `iced_wgpu` renderer. Cannot be used together with the `glow`
# feature.
wgpu = ["iced_wgpu"]
# Enables the `iced_glow` renderer. Cannot be used together with the `wgpu`
# feature.
glow = ["iced_glow", "baseview/opengl"]

# Enables a debug view in native platforms (press F12)
debug = ["iced_native/debug"]

# Enables the `Image` widget for the `wgpu` backend
wgpu_image = ["iced_wgpu/image"]
# Enables the `Svg` widget for the `wgpu` backend
wgpu_svg = ["iced_wgpu/svg"]

# Enables the `Canvas` widget
canvas = ["iced_graphics/canvas"]
# Enables the `QRCode` widget
qr_code = ["iced_graphics/qr_code"]

# Enables using system fonts
default_system_font = ["iced_graphics/font-source"]

# Enables advanced color conversion via `palette`
palette = ["iced_core/palette"]

# Enables `tokio` as the `executor::Default` on native platforms
tokio = ["iced_futures/tokio"]
# Enables `async-std` as the `executor::Default` on native platforms
async-std = ["iced_futures/async-std"]
# Enables `smol` as the `executor::Default` on native platforms
smol = ["iced_futures/smol"]

[dependencies]
baseview = { git = "https://github.com/RustAudio/baseview.git", rev = "b3712638bacb3fdf2883cb5aa3f6caed0e91ac8c" }
copypasta = "0.7.1"
iced_core = "0.5"
iced_futures = "0.4"
iced_glow = { version = "0.3", optional = true }
iced_graphics = "0.3"
iced_native = "0.5"
iced_wgpu = { version = "0.5", optional = true }
keyboard-types = { version = "0.6.1", default-features = false }
raw-window-handle = "0.4.3"
