[package]
name = "iced_baseview"
version = "0.0.1"
authors = ["Billy Messenger <BillyDM@protonmail.com>"]
edition = "2018"
description = "A baseview runtime for Iced (WIP)"
license = "MIT"
repository = "https://github.com/BillyDM/iced_baseview"
documentation = "https://docs.rs/iced_baseview"
keywords = ["gui", "ui", "graphics", "interface", "widgets"]
categories = ["gui"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["wgpu", "default_system_font"]
# Enables the `iced_wgpu` renderer
wgpu = ["iced_wgpu"]
# Enables the `Image` widget
image = ["iced_wgpu/image"]
# Enables the `Svg` widget
svg = ["iced_wgpu/svg"]
# Enables the `Canvas` widget
canvas = ["iced_wgpu/canvas"]
# Enables using system fonts.
default_system_font = ["iced_wgpu/default_system_font"]
# Enables the `iced_glow` renderer. Overrides `iced_wgpu`
glow = ["iced_glow", "iced_glutin"]
# Enables the `Canvas` widget for `iced_glow`
glow_canvas = ["iced_glow/canvas"]
# Enables using system fonts for `iced_glow`.
glow_default_system_font = ["iced_glow/default_system_font"]
# Enables a debug view in native platforms (press F12)
debug = ["iced_native/debug"]
# Enables advanced color conversion via `palette`
palette = ["iced_core/palette"]

[dependencies]
iced_native = { git = "https://github.com/hecrj/iced" }
iced_graphics = { git = "https://github.com/hecrj/iced" }
iced_core = { git = "https://github.com/hecrj/iced", optional = true }
baseview = { path = "../baseview" }
raw-window-handle = "0.3"
futures = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
iced_wgpu = { git = "https://github.com/hecrj/iced", optional = true }
iced_glutin = { git = "https://github.com/hecrj/iced", optional = true }
iced_glow = { git = "https://github.com/hecrj/iced", optional = true }