[package]
name = "iced_baseview"
version = "0.0.3"
authors = ["Billy Messenger <BillyDM@protonmail.com>"]
edition = "2018"
description = "A baseview runtime for Iced (WIP)"
license = "MIT"
repository = "https://github.com/BillyDM/iced_baseview"
documentation = "https://docs.rs/iced_baseview"
keywords = ["gui", "ui", "graphics", "interface", "widgets"]
categories = ["gui"]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["with-wgpu", "with-wgpu-default-system-font"]
# Enables the `wgpu` rendering backend
with-wgpu = ["iced_wgpu"]
# Enables the `Image` widget
with-wgpu-image = ["iced_wgpu/image"]
# Enables the `Svg` widget
with-wgpu-svg = ["iced_wgpu/svg"]
# Enables the `Canvas` widget
with-wgpu-canvas = ["iced_wgpu/canvas"]
# Enables using system fonts.
with-wgpu-default-system-font = ["iced_wgpu/default_system_font"]

# Enables the `glow` rendering backend
with-glow = ["iced_glow", "raw-gl-context", "glow"]
# Enables the `Canvas` widget
with-glow-canvas = ["iced_glow/canvas"]
# Enables using system fonts.
with-glow-default-system-font = ["iced_glow/default_system_font"]

# Enables a debug view in native platforms (press F12)
with-debug = ["iced_native/debug"]
# Enables `tokio` as the `executor::Default` on native platforms
with-tokio = ["iced_futures/tokio"]
# Enables `async-std` as the `executor::Default` on native platforms
with-async-std = ["iced_futures/async-std"]
# Enables advanced color conversion via `palette`
with-palette = ["iced_core/palette"]

[dependencies]
iced_core = { git = "https://github.com/iced-rs/iced.git", rev = "26d053a" }
iced_futures = { git = "https://github.com/iced-rs/iced.git", rev = "26d053a" }
iced_native =  { git = "https://github.com/iced-rs/iced.git", rev = "26d053a" }
iced_graphics = { git = "https://github.com/iced-rs/iced.git", rev = "26d053a" }
iced_wgpu = { git = "https://github.com/iced-rs/iced.git", rev = "26d053a", optional = true }
iced_glow = { git = "https://github.com/iced-rs/iced.git", rev = "26d053a", optional = true }
glow = { version = "0.11", optional = true }
raw-gl-context = { version = "0.1", optional = true }
keyboard-types = { version = "0.5", default-features = false }
baseview = { git = "https://github.com/RustAudio/baseview.git", rev = "004065e9a43e79751040879c572d95b9b63e0edc" }
raw-window-handle = "0.3"
log = "0.4"