[package]
name = "iced_baseview"
version = "0.0.3"
authors = [
  "Billy Messenger <BillyDM@protonmail.com>",
  "Robbert van der Helm <mail@robbertvanderhelm.nl>",
]
edition = "2021"
description = "A baseview runtime for Iced (WIP)"
license = "MIT"
repository = "https://github.com/BillyDM/iced_baseview"
documentation = "https://docs.rs/iced_baseview"
keywords = ["gui", "ui", "graphics", "interface", "widgets"]
categories = ["gui"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["wgpu"]

# Enables the `iced_wgpu` renderer. Cannot be used together with the `glow`
# feature.
wgpu = ["iced_wgpu"]
# Enables the `iced_glow` renderer. Cannot be used together with the `wgpu`
# feature.
glow = ["iced_glow", "baseview/opengl"]

# Enables a debug view in native platforms (press F12)
debug = ["iced_native/debug"]

# Enables the `Image` widget
image = ["iced_wgpu?/image", "iced_glow?/image"]
# Enables the `Svg` widget
svg = ["iced_wgpu/svg", "iced_glow?/svg"]
# Enables the `Canvas` widget
canvas = ["iced_wgpu?/canvas", "iced_glow?/canvas"]
# Enables the `QRCode` widget for the `wgpu` backend
qr_code = ["iced_wgpu?/qr_code", "iced_glow?/qr_code"]
# Enables using system fonts
default_system_font = ["iced_wgpu?/default_system_font", "iced_glow?/default_system_font"]
# Enables advanced color conversion via `palette`
palette = ["iced_core/palette"]

# Enables `tokio` as the `executor::Default` on native platforms
tokio = ["iced_futures/tokio"]
# Enables `async-std` as the `executor::Default` on native platforms
async-std = ["iced_futures/async-std"]
# Enables `smol` as the `executor::Default` on native platforms
smol = ["iced_futures/smol"]

[dependencies]
baseview = { git = "https://github.com/RustAudio/baseview.git", rev = "b3712638bacb3fdf2883cb5aa3f6caed0e91ac8c" }
cfg-if = "1"
copypasta = "0.8"
iced_core = "0.6"
iced_futures = "0.5"
iced_glow = { version = "0.4", optional = true }
iced_graphics = "0.4"
iced_native = "0.6"
iced_wgpu = { version = "0.6", optional = true }
keyboard-types = { version = "0.6", default-features = false }
raw-window-handle = "0.5"

[patch."https://github.com/RustAudio/baseview"]
baseview = { path = "../baseview" }
