[package]
name = "iced_baseview"
version = "0.0.3"
authors = ["Billy Messenger <BillyDM@protonmail.com>"]
edition = "2018"
description = "A baseview runtime for Iced (WIP)"
license = "MIT"
repository = "https://github.com/BillyDM/iced_baseview"
documentation = "https://docs.rs/iced_baseview"
keywords = ["gui", "ui", "graphics", "interface", "widgets"]
categories = ["gui"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["glow"]
# Enables the `wgpu` rendering backend
wgpu = ["iced_wgpu"]
# Enables the `Image` widget
image = ["iced_wgpu/image"]
# Enables the `Svg` widget
svg = ["iced_wgpu/svg"]
# Enables the `Canvas` widget
canvas = ["iced_wgpu/canvas"]
# Enables using system fonts.
default_system_font = ["iced_wgpu/default_system_font"]

# Enables the `glow` rendering backend
glow = ["iced_glow", "baseview/opengl"]
# Enables the `Canvas` widget
glow_canvas = ["iced_glow/canvas"]
# Enables using system fonts.
glow_default_system_font = ["iced_glow/default_system_font"]

# Enables a debug view in native platforms (press F12)
debug = ["iced_native/debug"]
# Enables `tokio` as the `executor::Default` on native platforms
tokio = ["iced_futures/tokio"]
# Enables `async-std` as the `executor::Default` on native platforms
async-std = ["iced_futures/async-std"]
# Enables advanced color conversion via `palette`
palette = ["iced_core/palette"]

[dependencies]
iced_core = "0.4"
iced_futures = "0.3"
iced_native =  "0.4"
iced_graphics = "0.2"
iced_wgpu = { version = "0.4", optional = true }
iced_glow = { version = "0.2", optional = true }
keyboard-types = { version = "0.6.1", default-features = false }
# This includes changes to make the OpenGL context creation
baseview = { git = "https://github.com/robbert-vdh/baseview.git", branch = "feature/mouse-event-modifiers" }
raw-window-handle = "0.4.2"
