name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Install XCB and GL dependencies
      run: |
        sudo apt update
        # baseview dependencies
        sudo apt install libgl-dev libx11-xcb-dev libxcb1-dev libxcb-dri2-0-dev libxcb-icccm4-dev libxcursor-dev libxkbcommon-dev libxcb-shape0-dev libxcb-xfixes0-dev
      if: contains(matrix.os, 'ubuntu')
    - name: Install rust stable
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --examples --workspace --verbose --features wgpu
    - name: Run tests
      run: cargo test --examples --workspace --verbose
